export const
	LEFT_DOUBLE_QUOTE = "“",
	RIGHT_DOUBLE_QUOTE = "”",
	LEFT_SINGLE_QUOTE = "‘",
	RIGHT_SINGLE_QUOTE = "’",

	LEFT_DOUBLE_QUOTE_HALFWIDTH = "“\ufe00",
	RIGHT_DOUBLE_QUOTE_HALFWIDTH = "”\ufe00",
	LEFT_SINGLE_QUOTE_HALFWIDTH = "‘\ufe00",
	RIGHT_SINGLE_QUOTE_HALFWIDTH = "’\ufe00",

	LEFT_DOUBLE_QUOTE_FULLWIDTH = "“\ufe01",
	RIGHT_DOUBLE_QUOTE_FULLWIDTH = "”\ufe01",
	LEFT_SINGLE_QUOTE_FULLWIDTH = "‘\ufe01",
	RIGHT_SINGLE_QUOTE_FULLWIDTH = "’\ufe01",

	HALFWIDTH_VS = "\ufe00",
	FULLWIDTH_VS = "\ufe01";
